export enum NftCreateStatus {
    NONE = 0,
    MINT_PROGRESSING,
    MINT_FAILED,
    MINT_SUCCEED,
    APPROVE_PROGRESSING,
    APPROVE_FAILED,
    APPROVE_SUCCEED,
    CREATEOFFER_PROGRESSING,
    CREATEOFFER_FAILED,
    CREATEOFFER_SUCCEED
  }